//! Assembles the documentation site: hand-written Markdown plus two fragments generated from the
//! code (the clap `Cli` struct and the `IssueSpec` table), into one self-contained HTML file.

use std::fmt::Write;
use std::io;
use std::path::Path;

use baccheck_cli::cli::Cli;
use baccheck_core::report::IssueId;
use clap::CommandFactory;
use pulldown_cmark::{html, CowStr, Event, Options, Parser, Tag};

const CARBON_CSS: &str = include_str!("../../baccheck-core/assets/carbon.min.css");
const DOCS_CSS: &str = include_str!("../assets/docs.css");

/// The four Diátaxis quadrants, in sidebar order.
#[derive(Clone, Copy, PartialEq)]
pub enum Group {
    Tutorial,
    HowTo,
    Reference,
    Explanation,
}

impl Group {
    fn label(self) -> &'static str {
        match self {
            Group::Tutorial => "Tutorial",
            Group::HowTo => "How-to guides",
            Group::Reference => "Reference",
            Group::Explanation => "Explanation",
        }
    }

    /// The singular label above a page title. Differs from `label` for how-to guides only.
    fn kicker(self) -> &'static str {
        match self {
            Group::HowTo => "How-to guide",
            other => other.label(),
        }
    }
}

/// One page of the site. The Markdown source is `docs/src/<slug>.md`.
pub struct Page {
    pub slug: &'static str,
    pub group: Group,
    pub title: &'static str,
    /// Set for a page whose source holds a generated block.
    pub generated: Option<Generated>,
}

/// A block generated from the code. The page source holds `marker` where the block goes.
pub struct Generated {
    pub marker: &'static str,
    pub fragment: fn() -> String,
}

const fn page(slug: &'static str, group: Group, title: &'static str) -> Page {
    Page {
        slug,
        group,
        title,
        generated: None,
    }
}

const fn generated(
    slug: &'static str,
    group: Group,
    title: &'static str,
    block: Generated,
) -> Page {
    Page {
        slug,
        group,
        title,
        generated: Some(block),
    }
}

pub const PAGES: [Page; 13] = [
    page(
        "tutorial-first-report",
        Group::Tutorial,
        "First capture to first report",
    ),
    page("howto-run", Group::HowTo, "Run a capture"),
    page("howto-read", Group::HowTo, "Read a finding"),
    page("howto-remediate", Group::HowTo, "Apply a remediation"),
    page("howto-severity", Group::HowTo, "Interpret severity"),
    generated(
        "ref-cli",
        Group::Reference,
        "CLI flags",
        Generated {
            marker: "<!-- GENERATED:cli-flags -->",
            fragment: cli_flags_fragment,
        },
    ),
    generated(
        "ref-issues",
        Group::Reference,
        "Issue catalogue",
        Generated {
            marker: "<!-- GENERATED:issue-catalogue -->",
            fragment: issue_catalogue_fragment,
        },
    ),
    page("ref-schema", Group::Reference, "Finding & Report schema"),
    page("ref-severity", Group::Reference, "Severity levels"),
    page("ref-floors", Group::Reference, "Evidence-floor semantics"),
    page(
        "exp-detectors",
        Group::Explanation,
        "How the detectors work",
    ),
    page("exp-bacnet", Group::Explanation, "BACnet/IP in brief"),
    page(
        "exp-floors",
        Group::Explanation,
        "Why evidence floors exist",
    ),
];

/// The CLI reference body, from the clap definitions, as Markdown.
pub fn cli_flags_fragment() -> String {
    let help = Cli::command().bin_name("baccheck").render_long_help();
    format!("```text\n{}\n```\n", help.to_string().trim_end())
}

/// The issue catalogue body, from the `IssueSpec` table, as Markdown.
pub fn issue_catalogue_fragment() -> String {
    let mut out = String::new();
    for issue in IssueId::ALL {
        let spec = issue.spec();
        let _ = writeln!(
            out,
            "### {}\n\nId: `{}`. Base severity: {}.\n\nRemediation steps:\n",
            spec.display_name,
            issue.as_str(),
            spec.base_severity.label()
        );
        for (n, step) in spec.remediation.iter().enumerate() {
            let _ = writeln!(out, "{}. {step}", n + 1);
        }
        out.push('\n');
    }
    out
}

fn render_markdown(page: &Page, source: &str) -> io::Result<String> {
    let mut source = source.to_string();
    if let Some(Generated { marker, fragment }) = &page.generated {
        if !source.contains(marker) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("{}.md has no {marker} marker", page.slug),
            ));
        }
        let block = format!(
            "<div class=\"doc-generated\">\n<span class=\"doc-generated__label\">Generated by \
             cargo xtask docs-build. Do not edit.</span>\n\n{}\n</div>\n",
            fragment()
        );
        source = source.replace(marker, &block);
    }
    // Page links are written as `other-slug.md`; the site is one file, so point at the page id.
    let events = Parser::new_ext(&source, Options::ENABLE_TABLES).map(|event| match event {
        Event::Start(Tag::Link {
            link_type,
            dest_url,
            title,
            id,
        }) => {
            let dest_url = match dest_url.strip_suffix(".md") {
                Some(slug) if !slug.contains("://") => CowStr::from(format!("#{slug}")),
                _ => dest_url,
            };
            Event::Start(Tag::Link {
                link_type,
                dest_url,
                title,
                id,
            })
        }
        other => other,
    });
    let mut body = String::new();
    html::push_html(&mut body, events);
    Ok(body)
}

/// Builds the whole site from the Markdown sources in `src_dir`.
pub fn build_site(src_dir: &Path) -> io::Result<String> {
    let mut nav = String::new();
    let mut pages = String::new();
    let mut current: Option<Group> = None;
    for page in &PAGES {
        if current != Some(page.group) {
            current = Some(page.group);
            let _ = writeln!(
                nav,
                "<div class=\"doc-nav__group-label\">{}</div>",
                page.group.label()
            );
        }
        let _ = writeln!(
            nav,
            "<a class=\"doc-nav__link\" href=\"#{slug}\" data-page=\"{slug}\">{}{}</a>",
            escape(page.title),
            if page.generated.is_some() {
                " <span class=\"doc-nav__tag cds--tag cds--tag--sm cds--tag--purple\">gen</span>"
            } else {
                ""
            },
            slug = page.slug
        );
        let source = std::fs::read_to_string(src_dir.join(format!("{}.md", page.slug)))
            .map_err(|e| io::Error::new(e.kind(), format!("{}.md: {e}", page.slug)))?;
        let body = render_markdown(page, &source)?;
        let _ = write!(
            pages,
            "<article class=\"doc-page\" id=\"page-{}\">\n<p class=\"doc-kicker\">{}</p>\n{body}</article>\n",
            page.slug,
            page.group.kicker()
        );
    }

    Ok(format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>BACcheck Documentation</title>\n\
         <style>{CARBON_CSS}</style>\n<style>\n{DOCS_CSS}</style>\n</head>\n<body>\n\
         <header class=\"doc-header\"><div class=\"doc-header__inner\">\
         <span class=\"doc-header__product\">BACcheck Docs</span></div></header>\n\
         <div class=\"doc-shell\">\n<nav class=\"doc-nav\" aria-label=\"Documentation\">\n{nav}</nav>\n\
         <main class=\"doc-main\">\n{pages}</main>\n</div>\n\
         <footer class=\"doc-footer\"><div class=\"doc-footer__inner\">\
         <span class=\"doc-footer__app\">BACcheck Docs</span>\
         <span class=\"doc-footer__credit\">MIT-licensed · Designed by \
         <a href=\"https://www.linkedin.com/in/benjamin-dw-truman/\" rel=\"noopener\">Benjamin D.W Truman</a>\
         </span></div></footer>\n<script>\n{SITE_JS}</script>\n</body>\n</html>\n"
    ))
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Shows the page named by the URL hash. Without JavaScript every page stays visible.
const SITE_JS: &str = "(function () {
  var root = document.documentElement;
  var first = document.querySelector('.doc-page').id.replace('page-', '');
  function show() {
    var slug = location.hash.slice(1) || first;
    if (!document.getElementById('page-' + slug)) { slug = first; }
    document.querySelectorAll('.doc-page').forEach(function (p) {
      p.classList.toggle('doc-page--active', p.id === 'page-' + slug);
    });
    document.querySelectorAll('.doc-nav__link').forEach(function (a) {
      a.classList.toggle('active', a.dataset.page === slug);
    });
    window.scrollTo(0, 0);
  }
  root.classList.add('js');
  window.addEventListener('hashchange', show);
  show();
})();
";
